In [4]:
%pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in d:\proyecto-ciber-ia\venv\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy in d:\proyecto-ciber-ia\venv\Lib\site-packages (2.5.3)
Requirement already satisfied: matplotlib in d:\proyecto-ciber-ia\venv\Lib\site-packages (3.11.1)
Requirement already satisfied: seaborn in d:\proyecto-ciber-ia\venv\Lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in d:\proyecto-ciber-ia\venv\Lib\site-packages (1.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\proyecto-ciber-ia\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\proyecto-ciber-ia\venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in d:\proyecto-ciber-ia\venv\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\proyecto-ciber-ia\venv\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in d:\proyecto-ciber-ia\venv\Lib\site-packages (from matplotlib) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\proyecto-ciber-ia\venv\Lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in d:\proyecto-ciber-ia\venv\Lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in d:\proyecto-ciber-ia\venv\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in d:\proyecto-ciber-ia\venv\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in d:\proyecto-ciber-ia\venv\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in d:\proyecto-ciber-ia\venv\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in d:\proyecto-ciber-ia\venv\Lib\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in d:\proyecto-ciber-ia\venv\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: cloudpickle>=3.0 in d:\proyecto-ciber-ia\venv\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.5 in d:\proyecto-ciber-ia\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
print(f"¡Éxito! Pandas versión: {pd.__version__}")

¡Éxito! Pandas versión: 3.0.5

In [6]:
import pandas as pd

print(f"Pandas versión: {pd.__version__}")

ruta_csv = "../data/raw/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv"
print(f"Ruta configurada: {ruta_csv}")

Pandas versión: 3.0.5
Ruta configurada: ../data/raw/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv

In [7]:
import numpy as np

print("Cargando el dataset... (esto puede tardar unos segundos por el tamaño)")
df = pd.read_csv(ruta_csv)


print(f"Forma original del dataset: {df.shape}")


df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)
print(f"Forma tras limpiar nulos/infinitos: {df.shape}")


display(df.head())


print("\nDistribución de clases (Tráfico Normal vs Ataques):")
print(df[' Label'].value_counts())

Cargando el dataset... (esto puede tardar unos segundos por el tamaño)
Forma original del dataset: (225745, 79)
Forma tras limpiar nulos/infinitos: (225711, 79)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,55054,109,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,55055,52,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,46236,34,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,54863,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

Distribución de clases (Tráfico Normal vs Ataques):
 Label
DDoS      128025
BENIGN     97686
Name: count, dtype: int64

In [8]:
import numpy as np

print("Cargando el dataset... (esto puede tardar unos segundos por el tamaño)")
df = pd.read_csv(ruta_csv)


print(f"Forma original del dataset: {df.shape}")

df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.dropna(inplace=True)
print(f"Forma tras limpiar nulos/infinitos: {df.shape}")

display(df.head())

print("\nDistribución de clases (Tráfico Normal vs Ataques):")
print(df[' Label'].value_counts())

Cargando el dataset... (esto puede tardar unos segundos por el tamaño)
Forma original del dataset: (225745, 79)
Forma tras limpiar nulos/infinitos: (225711, 79)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,55054,109,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,55055,52,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,46236,34,1,1,6,6,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,54863,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

Distribución de clases (Tráfico Normal vs Ataques):
 Label
DDoS      128025
BENIGN     97686
Name: count, dtype: int64